package main

import (
	"context"
	"log"
	"net"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	userv1 "github.com/meisam/buf-tutorial/gen/go/proto/user/v1"
)

// server implements the UserServiceServer interface generated by gRPC
type server struct {
	// For forward compatibility, it's a good practice to embed the unimplemented server
	// userv1.UnimplementedUserServiceServer
}

// GetUser is our actual RPC implementation
func (s *server) GetUser(ctx context.Context, req *userv1.GetUserRequest) (*userv1.GetUserResponse, error) {
	log.Printf("Received request for user ID: %d", req.GetId())

	// Simulated database lookup
	if req.GetId() != 101 {
		// Use standard gRPC status codes instead of HTTP 404
		return nil, status.Errorf(codes.NotFound, "user with id %d not found", req.GetId())
	}

	// Build the response
	return &userv1.GetUserResponse{
		User: &userv1.User{
			Id:    101,
			Name:  "Meisam",
			Email: "meisam@example.com",
		},
	}, nil
}
func LoggingInterceptor(ctx context.Context, req interface{}, info *grpc.UnaryServerInfo, handler grpc.UnaryHandler) (interface{}, error) {
	start_time := time.Now()

	excutaion, err := handler(ctx, req)

	if err != nil {
		log.Printf("failed to execute request: %v", err)
	}
	end_time := time.Since(start_time)

	log.Printf("request executed in %v, method: %v", end_time, info.FullMethod)

	return excutaion, nil
}
func main() {
	// 1. Listen on a TCP port
	lis, err := net.Listen("tcp", ":50051")
	if err != nil {
		log.Fatalf("Failed to listen: %v", err)
	}

	// 2. Create a new gRPC server instance
	grpcServer := grpc.NewServer(grpc.UnaryInterceptor(LoggingInterceptor))

	// 3. Register our service implementation with the gRPC server
	userv1.RegisterUserServiceServer(grpcServer, &server{})

	log.Println("gRPC Server listening on port 50051...")

	// 4. Start serving requests
	if err := grpcServer.Serve(lis); err != nil {
		log.Fatalf("Failed to serve: %v", err)
	}
}
