# Stage 1: The Builder (Contains all Go tools, but is very heavy)
FROM golang:alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy the go.mod and go.sum files first to cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of your source code
COPY . .

RUN go build -o inventory-service ./inventory/main.go

# Stage 2: The Final Image (Extremely lightweight, NO Go tools installed!)
FROM alpine:latest
WORKDIR /root/

COPY --from=builder /app/inventory-service .

CMD ["./inventory-service"]
